import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-courses-details',
  templateUrl: './courses-details.component.html',
  styleUrl: './courses-details.component.css',
})
export class CoursesDetailsComponent {
  courseId!: string;
  courseDetails: any;
  bulletPoints: any;
  lessons: any;
  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    // Get the course ID from the URL
    this.courseId = this.route.snapshot.paramMap.get('id')!; // Retrieve the 'id' param

    // For the purpose of this example, we'll mock the course details
    // In a real application, you would fetch this from an API or service based on the courseId.
    this.courseDetails = this.getCourseDetails(this.courseId);
  }

  getCourseDetails(id: string) {
    // Mock data, you can replace this with an actual service call
    const courses = [
      {
        id: '1',
        title: 'UI/UX',
        description:
          'Our UI/UX Design Training focuses on equipping you with the skills to create user-friendly, visually appealing, and intuitive digital experiences. Learn wireframing, prototyping, user research, and design tools like Figma and Adobe XD. Gain hands-on experience and build a portfolio to kickstart your career in design!',
        imgUrl: 'assets/img/course/13.jpg',
        bulletPoints: [
          'Research & Analysis',
          'Wireframing & Prototyping',
          'Information Architecture (IA)',
        ],
        lessons: [],
      },
      {
        id: '2',
        title: 'Data Analytics',
        description:
          'Unlock the power of data with our comprehensive Data Analytics Training. This program is designed for individuals looking to develop essential skills to analyze and interpret data, make data-driven decisions, and gain actionable insights.',
        imgUrl: 'assets/img/course/details/RMDA.png',
        bulletPoints: [
          'Hands-on Experience:Learn with real-world datasets using industry-standard tools like Excel, SQL, Python, and Power BI.',
          'Core Skills:Master data cleaning, exploratory data analysis (EDA), data visualization, and statistical analysis.',
          'Business Application:Learn to transform data into valuable insights to improve business processes.',
          'Expert Instruction:Learn from experienced data analysts and professionals with practical experience in the field.',
          'Certification:Earn a certification to showcase your expertise to potential employers.',
        ],
        lessons: [
          'Requirement Analytics',
          'Excel ',
          'SQL',
          'Power BI ',
          'EDA Analysis',
          'Azure Fundamentals',
          'ChatGPT ',
          'Tableau ',
          'EDA Analysis',
          'GitHub',
          'Statistics (Stats) ',
          'Python ',
          'Machine Learning Algorithms ',
          'Exploratory Data Analysis (EDA)',
        ],
      },
      {
        id: '3',
        title: 'Full Stack-Python',
        description:
          'This Full Stack with Python Training is designed for aspiring developers to learn both front-end and back-end technologies, with Python as the primary back-end language. The course covers the complete development process, from setting up servers to building dynamic, data-driven websites.',
        imgUrl: 'assets/img/course/details/RMFSD.png',
        bulletPoints: [
          'Back-End Development with Python:Master Flask/Django for building robust APIs and web applications.',
          'Front-End Technologies:Learn HTML, CSS, JavaScript, and popular front-end frameworks like React or Angular.',
          'Database Management:Understand relational (SQL) and NoSQL (MongoDB) databases, including data modeling and querying.',
          'Version Control & Deployment:Use Git for version control and deploy applications with platforms like Heroku or AWS.',
          'Building RESTful APIs:Develop, test, and consume APIs to integrate different services.',
          'Full Project Implementation: Build end-to-end applications, from front-end UI to back-end server and database integration.',
        ],
        lessons: [
          'Frontend',
          'HTML, CSS',
          'JavaScript',
          'Bootstrap',
          'jQuery',
          'Database',
          'MySQL',
          'Oracle',
          ' MongoDB',
          'Framework',
          'Angular/React',
          'Express',
          'Node.js',

          'Core Python',
          'Advanced Python',
          'Django/Flask',
          'Tools',
          'VS Code',
          'Eclipse ',
          'Spring Tool Suite',
          'Git',
          ' PyCharm',
        ],
      },
      {
        id: '4',
        title: 'Data Science',
        description:
          'Unlock the world of data with our comprehensive Data Science Training Program. Designed for beginners and professionals, this course covers essential tools, techniques, and methodologies used in data analysis and machine learning.',
        imgUrl: 'assets/img/course/details/RMDS.png',
        lessons: [
          'Analytics Introduction ',
          'Excel',
          'SQL',
          'Power BI ',
          'Azure Fundamentals',
          ' ChatGPT ',
          ' Tableau ',
          ' EDA Analysis',
          'Development Tools',
          ' GitHub',
          'Stats',
          ' Python',
          ' ML Algorithm ',
          'AI and Advanced Topics ',
          'Maths ',
          ' ML Advance ',
          ' NLP ',
          'Generative AI',
          'Time Series Modeling',
          'TensorFlow',
        ],
        bulletPoints: [
          'Hands-on Learning:Practical exercises with real-world datasets.',
          ' Comprehensive Curriculum:From data preprocessing and visualization to machine learning algorithms.',
          'Tools & Technologies:Python, R, SQL, and popular libraries like Pandas, NumPy, and Scikit-learn.',
          'Expert Instructors: Learn from industry experts with years of experience',
          'Project-Based: Work on live projects to build a solid portfolio',
          'Career Support: Job assistance and resume building.',
        ],
      },
      {
        id: '5',
        title: 'Digital Marketing',
        description:
          'Our Digital Marketing Training empowers you with in-demand skills in SEO, social media, Google Ads, email marketing, content strategy, and analytics. Gain hands-on experience, industry insights, and expert guidance to build a successful digital marketing career!',
        imgUrl: 'assets/img/course/details/RMDM.png',
        lessons: [
          'Digital Marketing Introduction Overview',
          'Landing Page Optimization',
          'Social Media Ad Companies',
          'Google Ads',
          ' Social Media Marketing',
          'Social Media Automation',
          'Search Engine',
          'Search Engine Optimization (SEO)',
          'Core Modules',
          'Planning and Creating a Website',
          'Google Algorithm',
          'Content Marketing Strategy',
          'Affiliate Marketing',
          'Video Marketing',
          'Capstone Projects',
          'Performance Measurements and Optimization',
          'Digital Marketing Strategy',
        ],
        bulletPoints: [
          'What You’ll Learn',

          'SEO Mastery: Optimize websites to rank higher on search engines',
          'Social Media Marketing: Build impactful campaigns on platforms like Facebook, Instagram, and LinkedIn.',
          'Content Marketing: Create compelling content to attract and retain customers.',
          'Google Ads & Analytics: Run effective ads and measure campaign performance.',
          'Email Marketing: Drive engagement and conversions with targeted email campaigns.',
        ],
      },
      {
        id: '6',
        title: 'Full Stack-JAVA',
        description:
          'This comprehensive Full Stack Java Developer Training equips you with the skills to develop and maintain both frontend and backend of web applications. The course covers a wide range of technologies used in modern web development, focusing on Java-based tools for the backend and frontend technologies for a complete development cycle.',
        imgUrl: 'assets/img/course/details/RMFSD.png',
        lessons: [
          'Frontend Development',
          'HTML & CSS',
          'JavaScript',
          'Bootstrap',
          'jQuery',
          'Database',
          'MySQL',
          'Oracle',
          'MongoDB',
          'Frameworks',
          'Angular/React',
          'Express.js',
          'Node.js',
          'Backend Development',
          'Core Java',
          'Advanced Java',
          'Hibernate',
          'Spring Boot',
          'Core Python',
          'Advanced Python',
          'Tools',
          'Code Editors and IDEs',
          'Version Control and Collaboration',
          'Spring Tool Suite',
          'Additional Tools',
        ],
        bulletPoints: [
          'Frontend Development: Learn HTML5, CSS3, JavaScript, and modern frameworks like Angular or React to build dynamic user interfaces.',
          'Backend Development: Master Java, Spring Boot, and Hibernate for building scalable, secure, and high-performance backend services.',
          'Databases: Understand SQL with MySQL, PostgreSQL, and NoSQL with MongoDB.',
          'RESTful APIs: Build and consume REST APIs for seamless communication between frontend and backend.',
          'Version Control: Learn Git for effective collaboration and code management.',
          'Deployment: Understand deployment techniques using Docker, AWS, or Heroku for cloud-based applications.',
          'Security: Implement basic security measures using Spring Security.',
          'Project Work: Hands-on projects to solidify your learning and showcase your skills in real-world applications.',
        ],
      },
      {
        id: '7',
        title: 'Business Analytics',
        description:
          'Our training and Internship program brighten your career journey with a Live Business Analyst Project and Helps to achieve your professional goals. Gain access to world-class training and internships designed to prepare you for success in the competitive business world. Elevate your skills with specialized training in requirements elicitation, process mapping, and business process modeling to cater to professionals at all levels from aspiring analysts to experienced practitioners.',
        imgUrl: 'assets/img/course/details/RMBA.png',
        lessons: [
          ' Introduction to Business Analysis',
          ' Excel',
          ' SQL',
          ' Power BI',
          'EDA Analysis',
          'Tableau',
          'GhatGPT',
          ' Azure Fundamentals',
          'GitHub',
          'Stats',
          'Python',
          ' Certification Preparation (Optional)',
        ],
        bulletPoints: [
          'Master data analysis using Excel, SQL, and advanced analytics tools.',
          'Learn how to visualize and interpret data with tools like Tableau and Power BI.',
          'Understand predictive analytics and its role in forecasting trends.',
          'Gain expertise in statistical modeling, hypothesis testing, and data mining.',
          'Develop skills to make data-driven decisions and optimize business outcomes.',
          'Real-world case studies and interactive exercises to reinforce learning.',
        ],
      },
      {
        id: '8',
        title: 'MERN-Stack',
        description:
          'Unlock the full potential of modern web development with our MERN Stack Training. Learn to build dynamic, high-performance applications using MongoDB, Express.js, React, and Node.js—the powerful technologies behind some of the most popular web apps today.',
        periods: '12 Periods',
        difficulty: 'Intermediate',
        instructor: 'Jane Doe',
        students: '8000+',
        feedback: '4.7',
        imgUrl: 'assets/img/course/details/RMMERN.png',
        lessons: [
          'Introduction to MERN Stack',
          'HTML',
          'CSS3',
          'JavaScript',
          'Bootstrap',
          ' Client-side Frontend',
          'React JS',
          'API with Express/Node.js',
          'Showing Database in MongoDB',
          'GitHub',
        ],
        bulletPoints: [
          'MongoDB: Master NoSQL databases, schema design, and data modeling.',
          'Express.js: Learn how to build scalable backend APIs with a fast, minimalist framework.',
          'React: Gain expertise in building responsive, interactive UIs with React.',
          'Node.js: Develop server-side applications using JavaScript.',

          'Full-Stack Development: Understand end-to-end web development, from database to frontend',
          'Real-World Projects: Hands-on training through practical projects for experience',
          'Job-Oriented Skills: Learn industry-relevant tools and best practices to excel in the job market',
        ],
      },
      {
        id: '9',
        title: 'MEAN-Stack',
        description:
          'This MEAN Stack training is designed to help you become proficient in building dynamic, modern web applications using MongoDB, Express.js, Angular, and Node.js. Learn how to develop full-stack applications with a powerful, JavaScript-based technology stack that covers both client-side and server-side development.',
        imgUrl: 'assets/img/course/details/RMMEAN.png',
        lessons: [
          'HTML',
          'CSS',
          'JavaScript',
          'Bootstrap',
          ' Client-side Frontend',
          'Angular JS',
          'API with Express/Node.js',
          'Showing Database in MongoDB',
          'GitHub',
        ],
        bulletPoints: [
          'MongoDB: Master NoSQL database design and management.',
          'Express.js: Learn to build scalable and high-performance back-end APIs.',
          'Angular: Gain expertise in creating dynamic, single-page applications (SPAs).',
          'Node.js: Understand server-side JavaScript programming for backend development.',
          'Hands-on Projects: Build real-world applications from scratch.',
          'RESTful APIs: Learn to create, consume, and manage APIs.',
          'End-to-End Development: Work through the entire development lifecycle with a unified JavaScript stack.',
        ],
      },
      {
        id: '10',
        title: 'Software Testing',
        description:
          'A software testing course equips learners with essential skills to identify and fix software defects, ensuring quality and reliability. It covers testing methods, tools, and best practices for manual and automated testing in real-world scenarios.',
        imgUrl: 'assets/img/course/details/RMST.png',
        bulletPoints: [
          'Comprehensive Curriculum: Learn manual testing, automation, and agile methodologies.',
          'Hands-on Experience: Work with popular tools like Selenium, JIRA, and Postman.',
          'Real-World Scenarios: Test applications with real-world cases to build confidence.',
          'Expert Instructors: Learn from industry professionals with extensive experience.',
          'Certification: Earn a valuable certification to showcase your expertise.',
        ],
        lessons: [
          'Getting Started with Software Testing',
          'Understanding the Requirements of Testing',
          'Fundamental of Software Testing',
          'Types of Testing',
          'Testing Levels',
          'Testing Life Cycle',
          'Best Practices',
          'Testing Automation',
          'Testing Techniques',
          'Manual Testing (JIRA, Excel)',
          'Purpose of Manual Testing',
          'Testing Types',
          'Testing Processes',
          'Test Case Development',
          ' Best Practices & Tools ',
          'Challenges in Manual Testing',
          'Models in Testing',
          'Waterfall Model',
          ' V-Model',
          ' Agile Model',
          ' Spiral Model',
          'SQL and Web Services Testing',
          'Introduction to SQL and its application in testing',
          'Mobile Testing',
          'Introduction to Mobile Testing',
          'Agile Testing',
          'Fundamentals of Agile Testing → Automated Testing',
          'Core Java and Testing Tools',
          'Core Java',
          ' API Testing (Postman)',
          'Selenium with JIRA',
          'Soft Skills and Career Preparation',
          'Soft Skills Session ',
          ' MCQs ',
          'Mock Interview Sessions',
          'Placement Preparation',
        ],
      },
      // Add more mock course data as needed
    ];

    return courses.find((course) => course.id === id);
  }
}
